Filter
nemisis84/SIPp-log-to-script pull request #9
Opened 2023-06-27 09:51 UTC by moltubaer

2023-06-27 11:05 UTC, nemisis84 commented
I suggest we make it a class so that it easier to pass into other files. One alternative could be to make a main method

2023-06-27 11:30 UTC, nemisis84 requested changes
Ser bra ut med noen småting. Jeg foretrekker OOP tilnærming

2023-06-27 11:30 UTC, nemisis84 commented on scripts/filter.py
> +        with open(logDirPath + ID + '.log', 'r') as file:
Give the open both read and write permissions when first opening it. We don't need to open it twice

2023-06-27 13:34 UTC, moltubaer commented on scripts/filter.py
> +    "fields": ["SIP/2.0", "From", "To", "Via", "Contact", "Call-ID", "CSeq", "Content-Length", "Max-Forwards", "Content-Type", "Route", "Record-Route"],
It is hard to filter out "Record-Route" without interfering with the filtering of "Route", with the current algorithm. I suggest leaving it as is.

2023-06-27 13:39 UTC, moltubaer commented on scripts/filter.py
> +    with open(output) as file:
I have to open it once for writing and a second time for reading. I have tried combining it with a "read/write" mode, but it has so far proven unsuccessful. It takes too much time for it to be worth it.

2023-06-28 08:41 UTC, nemisis84 approved these changes

2023-06-28 08:42 UTC, merged